SystemEgzaminacyjny/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemEgzaminacyjny.Service.Services.Interfaces;
using SystemEgzaminacyjny.Service.ViewModels.Answer;

namespace SystemEgzaminacyjny.Controllers
{
	[Authorize(Roles = "admin")]
    public class AnswerController : Controller
    {
		private readonly IAnswerService _answerService;

		public AnswerController(IAnswerService answerService)
		{
			_answerService = answerService;
		}
        // GET: Answer
        public ActionResult List(int questionId, int examId)
        {
			var model = new AnswerListViewModel()
			{
				Id = questionId,
				ExamId = examId,
				List = _answerService.GetByQuestionId(questionId)
			};

            return View(model);
        }

        // GET: Answer/Create
		public ActionResult Create(int questionId, int examId)
		{
			var model = new AnswerViewModel
			{
				QuestionId = questionId,
				ExamId = examId
			};

            return View(model);
        }

        // POST: Answer/Create
        [HttpPost]
        public ActionResult Create(AnswerViewModel model)
        {
            try
            {
				_answerService.Add(model);

				return RedirectToAction("List", new { questionId = model.QuestionId, examId = model.ExamId });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Answer/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_answerService.GetSingle(id));
        }

        // POST: Answer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, AnswerViewModel model)
        {
            try
			{
				_answerService.Update(model);

				return RedirectToAction("List", new { questionId = model.QuestionId, examId = model.ExamId });
            }
            catch
            {
                return View(model);
            }
        }

        // POST: Answer/Delete/5
		[HttpPost]
		public ActionResult Delete(int id)
		{
			_answerService.Delete(id);

			return Content(Boolean.TrueString);
		}
    }
}

SystemEgzaminacyjny/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemEgzaminacyjny.Service.Services.Interfaces;
using SystemEgzaminacyjny.Service.ViewModels.Question;

namespace SystemEgzaminacyjny.Controllers
{
	[Authorize(Roles = "admin")]
    public class QuestionController : Controller
    {
		private readonly IQuestionService _questionService;

		public QuestionController(IQuestionService questionService)
		{
			_questionService = questionService;
		}

        // GET: Question
        public ActionResult List(int examId)
        {
			var model = new QuestionListViewModel
			{
				Id = examId,
				List = _questionService.GetByExamId(examId)
			};

            return View(model);
        }

        // GET: Question/Create
		public ActionResult Create(int examId)
        {
			var model = new QuestionViewModel
			{
				ExamId = examId
			};

            return View(model);
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(QuestionViewModel model)
        {
            try
			{
				if (!ModelState.IsValid)
					return View(model);

				_questionService.Add(model);

				return RedirectToAction("List", new { examId = model.ExamId });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id, int examId)
        {
			return View(_questionService.GetSingle(id));
        }

        // POST: Question/Edit/5
        [HttpPost]
		public ActionResult Edit(int id, int examId, QuestionViewModel model)
        {
            try
            {
				_questionService.Update(model);

				return RedirectToAction("List", new { examId = model.ExamId });
            }
            catch
            {
                return View(model);
            }
        }

        // POST: Question/Delete/5
		[HttpPost]
		public ActionResult Delete(int id)
		{
			_questionService.Delete(id);

			return Content(Boolean.TrueString);
		}
    }
}

SystemEgzaminacyjny/Views/Question/Create.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Question.QuestionViewModel

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.ExamId)

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SystemEgzaminacyjny/Views/Question/Edit.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Question.QuestionViewModel

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
		@Html.HiddenFor(model => model.ExamId)

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SystemEgzaminacyjny/Views/Question/List.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Question.QuestionListViewModel

@{
	var removeOptions = new AjaxOptions
	{
		HttpMethod = "post",
		OnSuccess = "removeObject"
	};
}

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

<p>
	@Html.ActionLink("Dodaj nowe", "Create", new { examId = Model.Id }, new { @class = "btn btn-success" })
</p>

<table class="table">
    <tr>
        <th>Pytanie</th>
		<th></th>
    </tr>

@foreach (var item in Model.List) {
    <tr>
		<td>
			@Html.DisplayFor(model => item.Content)
		</td>

		<td class="text-nowrap">
			@Html.ActionLink("Edytuj", "Edit", new { id = item.Id, examId = Model.Id }, new { @class = "btn btn-default" })
			@Html.ActionLink("Odpowiedzi", "List", "Answer", new { questionId = item.Id, examId = Model.Id }, new { @class = "btn btn-default" })
			@using (Ajax.BeginForm("Delete", new { id = item.Id, examId = Model.Id }, removeOptions, new { style = "display: inline;" }))
			{
				<button class="btn btn-danger" data-toggle="confirmation" data-title="Czy napewno chcesz usunąć te pytanie?"
						data-btn-ok-class="btn-sm btn-danger" data-btn-ok-label="Tak" data-btn-cancel-class="btn-sm btn-default" data-btn-cancel-label="Nie" data-singleton="true" data-popout="true">
					Usuń
				</button>
			}
		</td>
    </tr>
}

</table>