SystemEgzaminacyjny/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemEgzaminacyjny.Service.Services.Interfaces;
using SystemEgzaminacyjny.Service.ViewModels.Enrollment;
using Microsoft.AspNet.Identity;

namespace SystemEgzaminacyjny.Controllers
{
    public class EnrollmentController : Controller
    {
		private readonly IEnrollmentService _enrollmentService;
		private readonly IExamService _examService;

		public EnrollmentController(IEnrollmentService enrollmentService, IExamService examService)
		{
			_enrollmentService = enrollmentService;
			_examService = examService;
		}

        // GET: Enrollment
		[Authorize(Roles = "admin")]
        public ActionResult List(int examId)
        {
			var model = new EnrollmentListViewModel
			{
				ExamId = examId,
				ExamTopic = _examService.GetSingle(examId).Topic,
				List = _enrollmentService.GetByExamId(examId)
			};
			
            return View(model);
        }

		[Authorize(Roles = "admin")]
		public ActionResult ListWithoutDate(int examId)
		{
			var model = new EnrollmentListViewModel
			{
				ExamId = examId,
				ExamTopic = _examService.GetSingle(examId).Topic,
				List = _enrollmentService.GetWithoutDate(examId)
			};

			return View(model);
		}

		public ActionResult YourList()
		{
			var model = new EnrollmentListViewModel
			{
				List = _enrollmentService.GetByUserId(User.Identity.GetUserId())
			};

			return View(model);
		}

		public ActionResult Score(int id)
		{
			return View(_enrollmentService.GetScoreForEnrollment(id));
		}

        // GET: Enrollment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Enrollment/Create
		//public ActionResult Create(int examId)
		//{
		//	var model = new EnrollmentCreateViewModel
		//	{
		//		ExamId = examId,
		//		UserId = User.Identity.GetUserId()
		//	};

		//	return View(model);
		//}

        // POST: Enrollment/Create
		[Authorize]
        [HttpPost]
        public ActionResult Create(int examId)
		{
			var userId = User.Identity.GetUserId();

			if (_enrollmentService.GetByExamId(examId).Count == 0)
			{
				_enrollmentService.Add(examId, userId);

				return Content(Boolean.TrueString);
			}
			var enrollment = _enrollmentService.GetUserEnrollmentForExam(userId, examId, false);

			if (enrollment == null)
			{
				_enrollmentService.Add(examId, userId);
			}
			else
			{
				_enrollmentService.Delete(enrollment.Id);
			}

			return Content(Boolean.TrueString);
        }

        // GET: Enrollment/Edit/5
		[Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
			return View(_enrollmentService.GetSingle(id));
        }

        // POST: Enrollment/Edit/5
		[Authorize(Roles = "admin")]
        [HttpPost]
		public ActionResult Edit(int id, EditEnrollmentViewModel model)
		{
			if(ModelState.IsValid)
			{
				_enrollmentService.UpdateExamDate(model);

				return RedirectToAction("List", new { examId = model.ExamId });
			}
			else
			{
				return View(model);
			}
        }

		// POST: Enrollment/Edit/5
		[Authorize(Roles = "admin")]
		[HttpPost]
		public ActionResult EditSelected(int examId, EnrollmentListViewModel model)
		{
			return View(model);
		}

		// POST: Enrollment/Edit/5
		[Authorize(Roles = "admin")]
		[HttpPost]
		public ActionResult EditSelected_Post(EnrollmentListViewModel model)
		{
			try
			{
				var list = model.List.FindAll(p => p.IsSelected);

				var newModel = new EnrollmentListViewModel
				{
					ExamId = model.List[0].ExamId,
					ExamDate = model.ExamDate,
					List = list
				};

				_enrollmentService.UpdateSelected(newModel);

				return RedirectToAction("List", new { examId = model.ExamId });
			}
			catch
			{
				return View("EditSelected", model);
			}
		}

        // POST: Enrollment/Delete/5
		[Authorize(Roles = "admin")]
		[HttpPost]
		public ActionResult Delete(int id)
		{
			_enrollmentService.Delete(id);
			return Content(Boolean.TrueString);
		}
    }
}

SystemEgzaminacyjny/Controllers/ExamController.cs
using MvcSiteMapProvider.Web.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemEgzaminacyjny.Service.Services.Interfaces;
using SystemEgzaminacyjny.Service.ViewModels.Exam;
using Microsoft.AspNet.Identity;

namespace SystemEgzaminacyjny.Controllers
{
    public class ExamController : Controller
    {
		private readonly IExamService _examService;
		private readonly IEnrollmentService _enrollmentService;
		private readonly IQuestionService _questionService;

		public ExamController(IExamService examService, IEnrollmentService enrollmentService, IQuestionService questionService)
		{
			_examService = examService;
			_enrollmentService = enrollmentService;
			_questionService = questionService;
		}

        // GET: Exam
        public ActionResult List()
        {
			var examList = _examService.GetAll();
			foreach (var item in examList)
			{
				//item.IsExamInProgress = _examService.IsExamInProgress(item.Id);
				item.IsUserEnrolled = _enrollmentService.GetUserEnrollmentForExam(User.Identity.GetUserId(), item.Id, false) != null ? true : false;
			}

			var model = new ExamListViewModel()
			{
				List = examList
			};
			
            return View(model);
        }

		[Authorize(Roles="admin")]
		[HttpGet]
		public ActionResult StartExam(int id)
		{
			var model = new StartExamViewModel()
			{
				ExamId = id,
				NumberOfQuestionsInExam = _questionService.GetNumberOfQuestionsInExam(id)
			};

			return View(model);
		}

		[Authorize(Roles = "admin")]
		[HttpPost]
		public ActionResult StartExam(StartExamViewModel model)
		{
			_examService.StartExam(model);

			return RedirectToAction("List");
		}

		[Authorize]
		public ActionResult EndExam(int id)
		{
			_examService.EndExam(id, User.Identity.GetUserId());

			return RedirectToAction("EndOfExam");
		}

		public ActionResult EndOfExam()
		{
			return View();
		}

		[Authorize]
		[HttpGet]
		public ActionResult GetQuestion(int id)
		{
			var question = _examService.GetQuestion(id);

			if (question == null || question.RemainingTime < DateTime.MinValue.Ticks)
			{
				_examService.EndExam(id, User.Identity.GetUserId());
				return RedirectToAction("EndOfExam");
			}

			return View(question);
		}

		[Authorize]
		[HttpPost]
		public ActionResult	SaveUserAnswer(GetQuestionViewModel model)
		{
			_examService.SaveUserAnswer(model.Id, model);

			return RedirectToAction("GetQuestion", new { id = model.Id });
		}

        // GET: Exam/Details/5
        public ActionResult Details(int id)
        {
			return View(_examService.GetSingle(id));
        }

        // GET: Exam/Create
		[Authorize(Roles="admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Exam/Create
		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
        public ActionResult Create(ExamViewModel model)
        {
            try
            {
				if (!ModelState.IsValid)
					return View(model);

				_examService.Add(model);

                return RedirectToAction("List");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Exam/Edit/5
		[Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
			return View(_examService.GetSingle(id));
        }

        // POST: Exam/Edit/5
		[Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(int id, ExamViewModel model)
        {
            try
            {
				_examService.Update(model);

                return RedirectToAction("List");
            }
            catch
            {
                return View(model);
            }
        }

        // POST: Exam/Delete/5
		[Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
			_examService.Delete(id);

			return RedirectToAction("List");
        }
    }
}

SystemEgzaminacyjny/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemEgzaminacyjny.Service.Services.Interfaces;
using SystemEgzaminacyjny.Service.ViewModels.Question;

namespace SystemEgzaminacyjny.Controllers
{
	[Authorize(Roles = "admin")]
    public class QuestionController : Controller
    {
		private readonly IQuestionService _questionService;

		public QuestionController(IQuestionService questionService)
		{
			_questionService = questionService;
		}

        // GET: Question
        public ActionResult List(int examId)
        {
			var model = new QuestionListViewModel
			{
				Id = examId,
				List = _questionService.GetByExamId(examId)
			};

            return View(model);
        }

        // GET: Question/Create
		public ActionResult Create(int examId)
        {
			var model = new QuestionViewModel
			{
				ExamId = examId
			};

            return View(model);
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(QuestionViewModel model)
        {
            try
			{
				if (!ModelState.IsValid)
					return View(model);

				_questionService.Add(model);

				return RedirectToAction("List", new { examId = model.ExamId });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id, int examId)
        {
			return View(_questionService.GetSingle(id));
        }

        // POST: Question/Edit/5
        [HttpPost]
		public ActionResult Edit(int id, int examId, QuestionViewModel model)
        {
            try
            {
				_questionService.Update(model);

				return RedirectToAction("List", new { examId = model.ExamId });
            }
            catch
            {
                return View(model);
            }
        }

        // POST: Question/Delete/5
		[HttpPost]
		public ActionResult Delete(int id)
		{
			_questionService.Delete(id);

			return Content(Boolean.TrueString);
		}
    }
}

SystemEgzaminacyjny/Views/Exam/Create.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Exam.ExamViewModel

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(m => m.Topic, new { @class = "col-md-2 control-label" })
			<div class="col-md-10">
				@Html.TextBoxFor(m => m.Topic, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Topic, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Duration, new { @class = "col-md-2 control-label" })
			<div class="col-md-2">
				@Html.EditorFor(m => m.Duration, new { htmlAttributes = new { @class = "form-control" } })
			</div>
			<div class="col-md-2">
				@Html.Label("min", new { @class = "col-md-2 control-label" })
			</div>
			<div class="col-md-2">
				@Html.ValidationMessageFor(m => m.Duration, "", new { @class = "text-danger" })
			</div>
		</div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SystemEgzaminacyjny/Views/Exam/Details.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Exam.ExamViewModel

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Topic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topic)
        </dd>

    </dl>
</div>

SystemEgzaminacyjny/Views/Exam/Edit.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Exam.ExamViewModel

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SystemEgzaminacyjny/Views/Exam/EndOfExam.cshtml
@{
    ViewBag.Title = "Koniec egzaminu";
}

<h2>Koniec egzaminu</h2>

SystemEgzaminacyjny/Views/Exam/GetQuestion.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Exam.GetQuestionViewModel

@{
    ViewBag.Title = "Egzamin";
}

<h2>Egzamin</h2>
<p>Czas do końca egzaminu: <span data-countdown="@Model.RemainingTime" data-enrollment="@Model.Id"></span></p>
<p>Pozostało pytań: @Model.RemainingQuestions</p>

@using (Html.BeginForm("SaveUserAnswer", "Exam"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
		@Html.HiddenFor(model => model.QuestionId)
		
		<h4>Pytanie: @Model.Question.Content</h4>
		<table class="table-condensed">
			@for (int i = 0; i < Model.Answers.Count; i++)
			{
				@Html.HiddenFor(model => model.Answers[i].Id)
				<tr>
					<td>
						@Html.EditorFor(model => model.UserAnswers[i])
					</td>
					<td>
						@Html.DisplayFor(model => model.Answers[i].Content)
					</td>
				</tr>
			}
		</table>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dalej" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SystemEgzaminacyjny/Views/Exam/List.cshtml
@using Microsoft.AspNet.Identity;
@model SystemEgzaminacyjny.Service.ViewModels.Exam.ExamListViewModel

@{
	var removeOptions = new AjaxOptions
	{
		HttpMethod = "post",
		OnSuccess = "removeObject"
	}; 
	
	var enrollOptions = new AjaxOptions
	{
		HttpMethod = "post",
		OnSuccess = "toggleEnroll"
	}; 
}

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

@if(User.IsInRole("admin"))
{
    @Html.ActionLink("Dodaj nowy", "Create", null, new { @class = "btn btn-success" })
}

<table class="table">
    <tr>
        <th>Id</th>
		<th>Temat</th>
		<th>Czas trwania</th>
		<th></th>
    </tr>

@foreach (var item in Model.List) {
    <tr>
		<td>
			@Html.DisplayFor(model => item.Id)
		</td>
		<td>
			@Html.DisplayFor(model => item.Topic)
		</td>
		<td>
			@Html.DisplayFor(model => item.Duration) min
		</td>
		<td class="text-nowrap">
			@if(User.IsInRole("admin"))
			{
				@Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
				@Html.ActionLink("Pytania", "List", "Question", new { examId = item.Id }, new { @class = "btn btn-default" })
				@using (Ajax.BeginForm("Delete", new { id = item.Id }, removeOptions, new { style = "display: inline;" }))
				{
					<button class="btn btn-danger" data-toggle="confirmation" data-title="Czy napewno chcesz usunąć egzamin i wszystkie jego komponenty?"
							data-btn-ok-class="btn-sm btn-danger" data-btn-ok-label="Tak" data-btn-cancel-class="btn-sm btn-default" data-btn-cancel-label="Nie" data-singleton="true" data-popout="true">
						Usuń
					</button>
				}
				@Html.ActionLink("Zapisy", "List", "Enrollment", new { examId = item.Id }, new { @class = "btn btn-success" })
				@Html.ActionLink("Rozpocznij egzamin", "StartExam", new { id = item.Id }, new { @class = "btn btn-success" })
			}
			@using (Ajax.BeginForm("Create", "Enrollment", new { examId = item.Id }, enrollOptions, new { @class = "enrollForm", examid = @item.Id, style = "display: inline;" }))
			{
				if(item.Enrollments.Count == 0 || !(item.IsUserEnrolled))
				{
					<button class="btn btn-success">
						Zapisz się
					</button>
				}
				else
				{
					<button class="btn btn-warning">
						Wypisz się
					</button>
				}
			}
		</td>
    </tr>
}

</table>

SystemEgzaminacyjny/Views/Exam/StartExam.cshtml
@model SystemEgzaminacyjny.Service.ViewModels.Exam.StartExamViewModel

<h2>@Html.MvcSiteMap().SiteMapTitle()</h2>

<p>Liczba pytań w egzaminie: @Model.NumberOfQuestionsInExam</p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.ExamId)

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfQuestions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfQuestions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfQuestions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassThreshold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassThreshold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassThreshold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Rozpocznij" class="btn btn-default" />
            </div>
        </div>
    </div>
}